# base hostname & protocol for your site, e.g. http://example.com
url: "https://tecnologiaeinformacao.netlify.app"

# The name of your site, e.g. ACME Corp.
title: "Tecnonlogia e Informação"
description: "Desenvolvimento de software, sites, e dicas do Windows. Informações precisas e extensas para você não perder nenhum detalhe."
author: "Fernando Bonfim"
author-desc: 'Sempre muito incomodado em ficar no rasinho.'
github: 'https://github.com/Fb16455'

# The root repository for your whole website.
baseurl: "/"

# This is specific for GitHub pages.
markdown: kramdown # markdown -> HTML transpiler.
highlighter: rouge # Rouge will make the proper markup to the snippets on the pages.
# About rogue - https://jekyllrb.com/docs/liquid/tags/#code-snippet-highlighting
# About rogue - https://vilcins.medium.com/syntax-highlight-with-rouge-in-jekyll-6bf9e45f9dda
# Themes - https://w3techs.com/technologies/details/cm-elementor

# This setting determine if the about page exists or not.
# This will trigger the insertion of all links that refer to
# the about page in the layouts, includes or any other file that
# checks this setting.
aboutPage: false

# Plugins - https://jekyllrb.com/docs/plugins/installation/
plugins:
  - jekyll-paginate

# Pagination
paginate: 10
paginate-path: "pages/page:num/"
# Note: Permalink must be ommited or it will cause the pagination to break.

# Files with _ in their names are ignored when generating the files
# that goes into _site folder.
# This lines prevents it from happening for the _redirects files
# since Netlify needs it to know where to send users that try to access
# a page that redrects to another one.
include: [_redirects]

exclude: [docs, assets/styles/sources, assets/scripts/sources, webpack.config.js]

# Collections
# Using collections_dir won't work well with post_url and link tags
collections_dir: categories
collections:
  java:
    title: "Java"
    description: "Aqui eu explico os conceitos e elementos básicos da linguagem Java, tudo de maneira simples, mas sem ignorar informações importantes."
    thumbnail: "./assets/imgs/java-thumbnail.png"
    output: true
    permalink: "/java/:title"
    card: true
  batch:
    title: "Batch"
    description: "Entenda os conceitos básicos da linguagem Batch e aprenda a utilizar essa linguagem para aproveitar melhor o CMD. "
    thumbnail: "./assets/imgs/batch-thumbnail.png"
    output: true
    permalink: "/batch/:title"
    card: true
  jekyll:
    title: "Jekyll"
    description: "Aqui eu explico tudo que você precisa aprender para desenvolver sites rápidos e seguros com Jekyll."
    thumbnail: "./assets/imgs/jekyll-thumbnail.png"
    output: true
    permalink: "/jekyll/:title"
    card: true
  tips:
    title: "Dicas e Truques em Programação, Windows e mais"
    description: "Aqui eu apresento algumas dicas e truques que "
    thumbnail: "./assets/imgs/tips-and-tricks-thumbnail.png"
    output: true
    permalink: "/tips/:title"
