# base hostname & protocol for your site, e.g. http://example.com
url: "https://tecnologiaeinformacao.netlify.app" 

# The name of your site, e.g. ACME Corp.
title: "Tecnonlogia e Informação" 

description: Desenvolvimento de software, sites, e dicas do Windows. Tudo isso sob a visão de um noob, mas com informações precisas e extensas para você não perder nenhum detalhe. 

# The root repository for your whole website.
baseurl: "/" 

# This is specific for GitHub pages.
markdown: kramdown # markdown -> HTML transpiler.
highlighter: rouge # Rouge will paint the code in <code> elements. 
# About rogue - https://jekyllrb.com/docs/liquid/tags/#code-snippet-highlighting
# About rogue - https://vilcins.medium.com/syntax-highlight-with-rouge-in-jekyll-6bf9e45f9dda
# Themes - https://w3techs.com/technologies/details/cm-elementor

# This setting determine if the about page exists or not. 
# This will trigger the insertion of all links that refer to
# the about page in the layouts, includes or any other file that
# checks this setting.
aboutPage: false

# Plugins - https://jekyllrb.com/docs/plugins/installation/
plugins:
  - jekyll-paginate

# Pagination
paginate: 10
paginate-path: "pages/page:num/"
# Note: Permalink must be ommited or it will cause the pagination to break.

# Files with _ in their names are ignored when generating the files
# that goes into _site folder.
# This lines prevents it from happening for the _redirects files 
# since Netlify needs it to know where to send users that try to access
# a page that redrects to another one.
include: [_redirects]
