backend:
  name: git-gateway
  branch: posts # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow
media_folder: "assets/images"
public_folder: "/assets/images/"
collections:
  - name: "batch"
    label: "Curso de Batch"
    description: >
      Um curso completo sobre a linguagem batch.
    folder: "categories/_batch"
    create: true
    publish: true
    editor:
      preview: false
    fields:
      - { name: "title", widget: "string" }
      - { name: "layout", widget: "string" }
      - { name: "permalink", widget: "string" }
      - { name: "description", widget: "text" }
      - { name: "categories", widget: "list", defalt: ["batch"] }
      - { name: "tags", widget: "list" }
      - { name: "date", widget: "datetime", date_format: "YYYY-MM-DD", time_format: "HH:mm:ss" }
      - { name: "lastUpdated", widget: "datetime", date_format: "YYYY-MM-DD", time_format: "HH:mm:ss" }
      - { name: "author", widget: "string" }
      - { name: "excerpt_separator", defalt: "<!--more-->" }
      - name: "source"
        fields:
          - { name: "title", widget: "string" }
          - { name: "url", widget: "string" }
        widget: "list"
        required: false
      - { name: "body", widget: "markdown" }
  - name: java
    label: "Curso de Java"
    folder: 'categories/_java'
    description: >
      Um curso completo sobre o Java.
    create: true
    publish: true
    editor:
      preview: false
    fields:
      - { name: "title", widget: "string" }
      - { name: "layout", widget: "string" }
      - { name: "permalink", widget: "string" }
      - { name: "description", widget: "text" }
      - { name: "categories", widget: "list", defalt: ["Java"] }
      - { name: "tags", widget: "list" }
      - { name: "date", widget: "datetime", date_format: "YYYY-MM-DD", time_format: "HH:mm:ss" }
      - { name: "lastUpdated", widget: "datetime", date_format: "YYYY-MM-DD", time_format: "HH:mm:ss" }
      - { name: "author", widget: "string" }
      - { name: "excerpt_separator", defalt: "<!--more-->" }
      - name: "source"
        fields:
          - { name: "title", widget: "string" }
          - { name: "url", widget: "string" }
        widget: "list"
        required: false
      - { name: "body", widget: "markdown" }
  - name: "jekyll"
    label: "Curso de Jekyll"
    folder: 'categories/jekyll'
    description: >
      Um curso completo sobre o Jekyll.
    create: true
    publish: true
    editor:
      preview: false
    fields:
      - { name: "title", widget: "string" }
      - { name: "layout", widget: "string" }
      - { name: "permalink", widget: "string" }
      - { name: "description", widget: "text" }
      - { name: "categories", widget: "list", defalt: ["batch"] }
      - { name: "tags", widget: "list" }
      - { name: "date", widget: "datetime", date_format: "YYYY-MM-DD", time_format: "HH:mm:ss" }
      - { name: "lastUpdated", widget: "datetime", date_format: "YYYY-MM-DD", time_format: "HH:mm:ss" }
      - { name: "author", widget: "string" }
      - { name: "excerpt_separator", defalt: "<!--more-->" }
      - name: "source"
        fields:
          - { name: "title", widget: "string" }
          - { name: "url", widget: "string" }
        widget: "list"
        required: false
      - { name: "body", widget: "markdown" }
  - name: "tips"
    label: "Dicas gerais"
    folder: 'categories/_tips'
    description: >
      Dicas de programação, sistemas operacionais, etc.
    create: true
    publish: true
    editor:
      preview: false
    fields:
      - { name: "title", widget: "string" }
      - { name: "layout", widget: "string" }
      - { name: "permalink", widget: "string" }
      - { name: "description", widget: "text" }
      - { name: "categories", widget: "list", defalt: ["batch"] }
      - { name: "tags", widget: "list" }
      - { name: "date", widget: "datetime", date_format: "YYYY-MM-DD", time_format: "HH:mm:ss" }
      - { name: "lastUpdated", widget: "datetime", date_format: "YYYY-MM-DD", time_format: "HH:mm:ss" }
      - { name: "author", widget: "string" }
      - { name: "excerpt_separator", defalt: "<!--more-->" }
      - name: "source"
        fields:
          - { name: "title", widget: "string" }
          - { name: "url", widget: "string" }
        widget: "list"
        required: false
      - { name: "body", widget: "markdown" }
  - name: "drafts"
    label: "Rascunhos"
    folder: "categories/_drafts"
    description: >
      Ideias de posts.
    create: true
    publish: true
    editor:
      preview: false
    fields:
      - { name: "title", widget: "string" }
      - { name: "layout", widget: "string" }
      - { name: "permalink", widget: "string" }
      - { name: "description", widget: "text" }
      - { name: "categories", widget: "list", defalt: ["batch"] }
      - { name: "tags", widget: "list" }
      - { name: "date", widget: "datetime", date_format: "YYYY-MM-DD", time_format: "HH:mm:ss" }
      - { name: "lastUpdated", widget: "datetime", date_format: "YYYY-MM-DD", time_format: "HH:mm:ss" }
      - { name: "author", widget: "string" }
      - { name: "excerpt_separator", defalt: "<!--more-->" }
      - name: "source"
        fields:
          - { name: "title", widget: "string" }
          - { name: "url", widget: "string" }
        widget: "list"
        required: false
      - { name: "body", widget: "markdown" }
