backend:
  name: git-gateway
  branch: posts # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow
media_folder: "assets/images"
public_folder: "/assets/images/"

collections:
  - name: batch
    label: "Curso de Batch"
    description:
      > Um curso completo sobre a linguagem batch.
    folder: "categories/batch"
    create: true
    publish: true
    editor:
      preview: false
    fields:
      - { name: "title" widget: "string" }
      - { name: "layout" widget: "string" }
      - { name: "permalink" widget: "string" }
      - { name: "description" widget: "text" }
      - { name: "categories" widget: "list" defalt: ["batch"] }
      - { name: "tags" widget: "list" }
      - { name: "date" widget: "DateTime" date_format: "YYYY-MM-DD" time_format: "HH:mm:ss" }
      - { name: "lastUpdated" widget: "DateTime" date_format: "YYYY-MM-DD" time_format: "HH:mm:ss" }
      - { name: "author" widget: "string" }
      - { name: "excerpt_separator: <!--more-->" }
      - name: "source"
        fields:
          { name: "title" widget: "string" }
          { name: "url" widget: "string" }
        widget: "list"
        required: false


  - name: java
    label: "Curso de Java"
  - name: jekyll
    label: "Curso de Jekyll"
  - name: tips
    label: "Dicas gerais"
  - name: drafts
    label: "Rascunhos"
